### ISSUE TITLE
Fails to install: Cannot find module "nan"

### ISSUE THREAD

**Issue by gordonwritescode** [indutny/node-nat-upnp#18]
Looks like the *netroute* package has some issue building the *nan* package.

```
$ npm install nat-upnp                                                                                                                                                                  *[master] 
-
> netroute@0.2.5 install /home/gordonhall/devel/libmuttr/node_modules/nat-upnp/node_modules/netroute
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
module.js:338
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/gordonhall/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-49-generic
gyp ERR! command "node" "/home/gordonhall/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gordonhall/devel/libmuttr/node_modules/nat-upnp/node_modules/netroute
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-49-generic
npm ERR! argv "/home/gordonhall/.nvm/versions/node/v0.12.0/bin/node" "/home/gordonhall/.nvm/versions/node/v0.12.0/bin/npm" "install" "nat-upnp"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! netroute@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netroute@0.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the netroute package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls netroute
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gordonhall/devel/libmuttr/npm-debug.log
```

Any ideas?

**Comment by gordonwritescode** [comment]
Actually it looks like this may be fixed in the latest commit that removes netroute.
